### ISSUE TITLE
Yarn is busy by another process

### ISSUE THREAD

**Issue by izio38** [spritsail/fivem#13]
Hi,

I've just tested your image, but I needed it for RedM, so I edited it a bit.

The console output from the container: 
![image](https://user-images.githubusercontent.com/9900846/70854652-c7a01c80-1ebe-11ea-8741-0d9e7d04b730.png)

My Docker-compose file:

```
  server:
    build:
      context: ./stacks/server
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/stacks/server/resources:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: "..."
```

I added a line to the entrypoint:
```
exec /opt/cfx-server/FXServer \
       +set citizen_dir /opt/cfx-server/citizen/ \
       +exec /config/server.cfg \
       +set sv_licenseKey ${LICENCE_KEY} \
       +set gamename rdr3 \
       $@
```

What could be wrong here?

I've tested on WSL, it works fine without docker tho :/

EDIT: Just to provide more informations, it looks like they changed the yarn builder from the `cfx-server-data`. I'm trying to find what's wrong here
