### ISSUE TITLE
Couldn't find resource

### ISSUE THREAD

**Issue by JanisPlayer** [spritsail/fivem#21]
Solution:
You have to transfer a folder not a file, ahh: D
```
version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ".config:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: "<nop sorry :D>"
```

I can't get to the server, my client loads scripts endlessly and there are errors in the server, the resources are not found.

 And I want to install fivepd, for that I want to create a database (mariadb) in Docker.
 But I only know about LXC / LXD, is it easy to implement or should I use LXC / LXD instead of Docker?

https://gtapolicemods.com/index.php?/forums/topic/478-fivepd-how-to-install/

Dont work:
```
docker run -d \
  --name FiveM \
  --restart=on-failure \
  -e LICENCE_KEY=<your-license-here>
  -p 30120:30120 \
  -p 30120:30120/udp \
  -v /volumes/fivem:/config \
  -ti \
  spritsail/fivem
```
Top level object in './docker-compose.yml' needs to be an object not '<class 'str'>'.

Work but this:
```
version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/home/fivem/config:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: "<nop sorry :D>"
```

`root@vmd47190:/home/fivem# docker image rm spritsail/fivem:latest
Untagged: spritsail/fivem:latest
Untagged: spritsail/fivem@sha256:fe6a27927210fe989df5198289fc7028788f5cd9c7f783bae5620d6513b17a2f
Deleted: sha256:ab0a880469865ed473105ecfcc539bff67adcecf24f61803b43975615bd285f4
Deleted: sha256:00eb7185db7238fd79ccb9b9f33d6beea796c492af21e7af8f42c7b08d36e141
Deleted: sha256:8df87b58cd20c457ff3229ab8b8a7655dd756e5ce98b651a4c2127816330174f
root@vmd47190:/home/fivem# docker-compose up
Pulling fivem (spritsail/fivem:)...
latest: Pulling from spritsail/fivem
d8f3f8ce52f0: Pull complete
f853bff20551: Pull complete
Digest: sha256:fe6a27927210fe989df5198289fc7028788f5cd9c7f783bae5620d6513b17a2f
Status: Downloaded newer image for spritsail/fivem:latest
Creating fivem ... done
Attaching to fivem
fivem    | Creating script environments for _cfx_internal
fivem    | Found new resource webadmin in /opt/cfx-server/citizen//system_resources//webadmin
fivem    | Found new resource monitor in /opt/cfx-server/citizen//system_resources//monitor
fivem    | Couldn't find resource sessionmanager.
fivem    | Creating script environments for webadmin
fivem    | Instantiated instance of script FxWebAdmin.BaseServer.
fivem    | Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
fivem    | Started resource webadmin
fivem    | Creating script environments for monitor
fivem    | Started resource monitor
fivem    | Couldn't find resource mapmanager.
fivem    | Couldn't find resource chat.
fivem    | Couldn't find resource spawnmanager.
fivem    | Couldn't find resource sessionmanager.
fivem    | Couldn't find resource fivem.
fivem    | Couldn't find resource hardcap.
fivem    | Couldn't find resource rconlog.
fivem    | Couldn't find resource scoreboard.
fivem    | Authenticating server license key...
fivem    | Server license key authentication succeeded. Welcome!
fivem    | cfx> Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
fivem    | Authenticating with Nucleus...
fivem    | server thread hitch warning: timer interval of 3673 milliseconds
fivem    |         fff
fivem    |   cccc ff   xx  xx     rr rr    eee
fivem    | cc     ffff   xx       rrr  r ee   e
fivem    | cc     ff     xx   ... rr     eeeee
fivem    |  ccccc ff   xx  xx ... rr      eeeee`

I think the link is wrong,
```
 && wget -O- http://github.com/citizenfx/cfx-server-data/archive/${DATA_VER}.tar.gz \
        | tar xz --strip-components=1 -C opt/cfx-server-data \
    \
```
https://github.com/citizenfx/cfx-server-data
Although not really but something is not.
http://github.com/citizenfx/cfx-server-data/archive/dd38bd01923a0595ecccef8026f1310304d7b0e3.tar.gz

Neither, it is probably due to folder's starting position.
With a Linux system on a normal system, it only worked where I was in the folder:
cd / home / FiveM / server-data / war
and then:
bash /home/FiveM/server/run.sh + exec /home/FiveM/server-data/server.cfg
Have executed.
