### ISSUE TITLE
Webpack is busy

### ISSUE THREAD

**Issue by Justus-Braun** [spritsail/fivem#68]
I created a server using this compose and txadmin installation

```
services:
  fivem:
    image: spritsail/fivem:stable
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./server-data/:/config"
      - "./txData/:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    environment:
      LICENSE_KEY: "${LICENSE_KEY}"
      NO_DEFAULT_CONFIG: "true" 

  database:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - './mariadb/:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
  ````

i used this recipe for the server-data:
https://raw.githubusercontent.com/overextended/ox_recipes/ox/recipe.yaml

But now screenshot-basic is stuck loading when booting the server.

Serverlog:
[fxserver_1705412057.log](https://github.com/spritsail/fivem/files/13950690/fxserver_1705412057.log)
