### ISSUE TITLE
This server does not have a license key specified

### ISSUE THREAD

**Issue by thoo0224** [spritsail/fivem#69]
When I try to run my docker compose, it gives me an error that the license key is not specified but I'm passing it with environment. In the entrypoint I'm printing `CONFIG_ARGS` and it is passing the license key correctly.

My docker-compose:
```yml
  server_esx:
    image: spritsail/fivem
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - database
    environment:
      - LICENSE_KEY=${LICENSE_KEY}
      - NO_DEFAULT_CONFIG=true
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    volumes:
      - ./esx:/config
      - ./volumes/esx:/txData
      - ./shared:/config/resources/[shared]
```

Error:
```
 [svadhesive] Error: This server does not have a license key specified.
 Please set the sv_licenseKey console variable to a key from https://keymaster.fivem.net/. 
(for example, `set sv_licenseKey "key"` in the config, or `+set sv_licenseKey key` on the command line)
```
