### ISSUE TITLE
TXAdmin env var not work

### ISSUE THREAD

**Issue by norfair00** [spritsail/fivem#75]
Hello,

`TXHOST_` Environment Configuration not work
<https://github.com/tabarra/txAdmin/blob/master/docs/env-config.md>
```yaml
version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.txadmin-http.rule: "Host(``)"
      traefik.http.routers.txadmin-http.entrypoints: "http"
      traefik.http.routers.txadmin-http.middlewares: "to-https@file"
      traefik.http.routers.txadmin-https.rule: "Host(``)"
      traefik.http.routers.txadmin-https.entrypoints: "https"
      traefik.http.routers.txadmin-https.tls: true
      traefik.http.routers.txadmin-https.tls.certResolver: "cloudflare"
      traefik.http.services.txadmin-https.loadbalancer.server.port: 40120
      traefik.docker.network: "proxy"
    environment:
      NO_DEFAULT_CONFIG: true
      TXHOST_PROVIDER_NAME: "xxxxxxxxxxxxx"
      TXHOST_PROVIDER_LOGO: "https://xxxxxxxxxxxxxx/xxxxxxxxxxxxx.png"
      TXHOST_DEFAULT_ACCOUNT: "xxxxxxxxx:000000:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ports:
      - "xxx.xxx.xxx.xxx:30120:30120"
      - "xxx.xxx.xxx.xxx:30120:30120/udp"
    volumes:
      - "/opt/fivem/srvdata:/config"
      - "/opt/fivem/txdata:/txData"
    networks:
      - database
      - proxy

networks:
  database:
    external:
      name: database
  proxy:
    external:
      name: proxy

```
